version: '3'
services:
  php:
    container_name: finviz-php
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: ./
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
      dockerfile: ./etc/docker/Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./:/var/www/html/
      - ./etc/docker/php/conf:/etc/apache2/sites-available/
      - ~/.ssh:/root/.ssh
      - ./etc/docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8001:80
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: finviz-mysql
    image: mysql
    volumes:
    - ./etc/docker/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=finviz
    ports:
    - 3308:3306

  rabbitmq:
    container_name: finviz-rabbitmq
    image: rabbitmq:3.7-management
    ports:
        - "5673:5672"
        - "32769:15672"

  mail:
    platform: linux/amd64
    container_name: finviz-mail
    image: mailhog/mailhog
    ports:
      - "8027:8025"
      - "1027:1025"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: finviz-elasticsearch
    ports: [ '9204:9200' ]
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
      - "xpack.security.enabled=false"
      - "network.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - './etc/docker/elasticsearch:/usr/share/elasticsearch/data'
