name: publish-develop

on:
  push:
    branches:
      - master
jobs:
  up-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: SCP files to server VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: .
          target: /var/www/production

  build:
    runs-on: ubuntu-latest
    needs: up-files

    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www
            chown -R www-data:www-data production/
            cd production/
            sudo -u www-data composer install
            bin/console cache:clear --env=prod